### ISSUE TITLE
403 forbidden on bintray Release

### ISSUE THREAD

**Issue by sibbl** [mpmc/tvheadend#55]
When accessing https://dl.bintray.com/mpmc/deb/Release, I get a 403 Forbidden. Has anything changed about where I can access the builds?

**Comment by mpmc** [comment]
Sorry about the error - I've been rate limited by bintray (again). when it's back up I'll look into mirroring it.

Please give it a few days.

**Comment by mpmc** [comment]
This should be "resolved" now.
