### ISSUE TITLE
Stable Ubuntu 18.04 repo

### ISSUE THREAD

**Issue by nerthazrim** [mpmc/tvheadend#85]
Hi,

I noticed that Ubuntu 18.04 'bionic' repo was present in http://apt.tvheadend.org/unstable/dists/ but not in the stable branch.

Has it been forgotten, or is it still in testing phase? :)

Anyway, appreciate all your work, thanks a lot!

**Comment by mpmc** [comment]
I'm looking into it :)

**Comment by nerthazrim** [comment]
Hey @mpmc, any news on this, to I can use the right repo and we can close this? :)

**Comment by mpmc** [comment]
unfortunately I don't have access to the server or know how to configure uploads from doozer to the repo to fix this. I hope that it's resolved ASAP. In the mean time you can use the third party ppa from Michael Marley, http://tvheadend.org/projects/tvheadend/wiki/AptRepository#Ubuntu-PPA

**Comment by mpmc** [comment]
resolved with 35b83ee672b99b0a7f50478220deb93ff165f10c
