### ISSUE TITLE
Persistance Problem using Raspberry Build 4.2.5-18~g951777a51

### ISSUE THREAD

**Issue by Marty56** [mpmc/tvheadend#91]
I am using build 4.2.5-18~g951777a51 on Raspberry Stretch.
I also have to use IP binding for my tuners.
Two persistance bugs

1. Every time the tvheadend service is stopped the related IPs in the tuner settings are lost.

2. Also I noted that this build is lossing track of recorded TV shows when the raspi reboots
Right now e.g. it shows 0 recorded shows allthough the related folder contains 10 recordings

**Comment by mpmc** [comment]
1. 4.2.5.18 is old. 4.2.6.16 is out now.
2. Do you see any errors when starting tvheadend? Stop the current service & run it from terminal.

```
sudo service tvheadend stop
sudo -u hts /usr/bin/tvheadend -c /home/hts/.hts/tvheadend
```
3. The startup log may show why the recordings are missing. However there was an issue on tvheadend.org mentioning issues with recordings disappearing and the latest Chrome. Try another browser.

**Comment by Marty56** [comment]
Thanks for the reply!

Could please do me another favour.
Since I am very new to tvheadend could you please provide instructions how to upgrade tvheadend without loosing the configuration,

**Comment by mpmc** [comment]
If you're on Raspbian Stretch & using my repo, you just need to `sudo apt update;sudo apt upgrade` :)

**Comment by Marty56** [comment]
Thanks. The update ran through but tvheadend was not updated. So probably I am not using your repro.
When I installed tvheadend 8 months ago I followed the instruction given under
https://tvheadend.org/projects/tvheadend/wiki/AptRepository   further down the page.

I seems that you repro was not added. 
Is is possible to "add" you repro after the fact?

**Comment by mpmc** [comment]
Yes.

**Comment by Marty56** [comment]
Good. I have tried
echo "deb https://dl.bintray.com/mpmc/deb raspbianstretch stable-4.2" | sudo tee /etc/apt/sources.list.d/tvheadend.list

and then sudo apt update;sudo apt upgrade
but no success. Sorry I am not the Linux expert.

**Comment by mpmc** [comment]
Go to the about page in the webui and copy/paste the version/or a screenshot :)

Also do apt show tvheadend, see what version it lists. :)

**Comment by Marty56** [comment]
the version shown by apt show tvheadend 

`Package: tvheadend
Version: 4.2.5-18~g951777a51~raspbianstretch
Status: install ok installed
Priority: extra
Section: video

Maintainer: Adam Sutton <aps@tvheadend.org>
Installed-Size: 19.9 MB
Depends: libavahi-client3 (>= 0.6.16), libavahi-common3 (>= 0.6.16), libc6 (>= 2.14), libdbus-1-3 (>= 1.9.14), libssl1.1 (>= 1.1.0), liburiparser1 (>= 0.6.0), zlib1g (>= 1:1.1.4), dvb-apps, bzip2
Recommends: xmltv-util
Replaces: hts-tvheadend
Enhances: showtime
Homepage: https://tvheadend.org
Download-Size: unknown
APT-Manual-Installed: yes
APT-Sources: /var/lib/dpkg/status
Description: Tvheadend
 Tvheadend is a TV streaming server and digital video recorder.
   - supports a variety of inputs (DVB-S(2)/T(2)/C, ISDB-S/T/C, ATSC-T/C, IPTV, SAT>IP, HDHR)
   - supports a variety of clients (Showtime, Smart TV, Kodi, VLC)`

and the about screen says

`HTS Tvheadend 4.2.5-18~g951777a51
© 2006 - 2017 Andreas Öman, Jaroslav Kysela, Adam Sutton, et al.

https://tvheadend.org
Based on software from ExtJS. Icons from FamFamFam
Build: 4.2.5-18~g951777a51 (2018-01-23T02:08:20+0000) Toggle details
If you'd like to support the project, please consider a donation.
All proceeds are used to support server infrastructure and buy test equipment.`

**Comment by Marty56** [comment]
Ok. I think I could solve it by changing the rights of file and folder unter /home/hts to 777.
The inability not to update is not so important anymore because stability wise the old version is running perfectly fine.

**Comment by mpmc** [comment]
Well, from that info, you manually installed it via dpkg (at least someone did). If you wanted to use the latest you could just sudo apt-get remove tvheadend;sudo apt-get autoremove. 

Then follow the Apt repo instructions and you should be good to go. Setting 777 on folders is never a good idea.

If you don't mind redoing the config, just purge the package, user and home folder & re-install :)

**Comment by Marty56** [comment]
Thanks for the support.

**Comment by Marty56** [comment]
Ok. I have changed the owner of /home/hts to hts and then changed permissions to 744.
This should be better. I was not sure whether the right "execute" is needed or not.
